### PR TITLE
updated JSONs

### PR DESCRIPTION
**Pull request by lucagiovannini7**
Here another group of updated JSONs. One issue though: Early Print texts have quite often messy markup, with stage directions marked as speech acts, speech acts, speakers and/or stage directions not recognised etc. In the first case, I marked them with the artificial who-tag `none`, since I didn't know if I was allowed to simply delete the speech instance from the JSON. If it is possible, please do so.

At least for some files, which I need for my dissertation, I would definitely like to do some corrections directly on the XMLs, but if these changes cannot be preserved with every "update" of the living corpus it seems pointless to do so (this applies also to what we did for the vanilla corpus). By the way, do we plan to implement some automated updating system for this task?

### CODE REVIEW

**Review by cmil — COMMENTED** [review]
Hi Luca, several of the files have syntax errors, mostly either missing or too many commas. Can you please correct those errors (in A01353.json, A11145.json, A27177_29.json, A29360.json, A36759.json as far as I can see). Maybe use an editor that supports syntax highlighting and error reporting for JSON. Visual Studio Code would be a free one that should support that out of the box.

The bogus speeches do not need to be marked with a `none` ID. They can just be deleted or left empty.

Corrections of markup mistakes should ideally be done in epdracor-sources to integrate them into the transformation workflow.

So far I don't plan any further automation of the workflow. However, it should be possible to set up our system so that you can run the transformation script and check the result yourself.

**Comment by lucagiovannini7** [comment]
> several of the files have syntax errors

Ok, I'll fix them. Sorry for the errors. I work with Notepad++ and it does not help in this sense, I'll try the software you mentioned. As I already said, I find this workflow sub-optimal and quite difficult to follow with respect to straightforward XML editing. 

>  I don't plan any further automation of the workflow.

But are you still planning to pull regular updates from the EP source corpus _manually_, right? This would somehow justify  the extra work to keep EPDraCor a "living corpus" (I'm speaking of the changes from the EP side, not of our DraCor transformations).

> Corrections of markup mistakes should ideally be done in epdracor-sources to integrate them into the transformation workflow

So, if I understand that correctly, is it possible to correct markup in `epdracor-sources` **with the changes being preserved** with every update from the source corpus? Or does any new update rewrite the `sources` repository, making this work useless? Thanks for clarifying!

**Comment by lucagiovannini7** [comment]
Hi @cmil, I corrected the syntax errors via the "Problems" tool in Visual Studio Code. The files should be fine now.

**Comment by lucagiovannini7** [comment]
Hello @cmil , it would be great if you could either approve this commit or provide feedback, since I need these plays (in their corrected version) for my dissertation. Thanks.

**Comment by cmil** [comment]
Hi @lucagiovannini7, sorry, this dropped from my radar.

> > several of the files have syntax errors
> 
> Ok, I'll fix them. Sorry for the errors. I work with Notepad++ and it does not help in this sense, I'll try the software you mentioned. As I already said, I find this workflow quite difficult to follow with respect to straightforward XML editing.

There are still four invalid JSON files. I will correct them after merging. Notepad might not be the best of tools nowadays. 

> 
> > I don't plan any further automation of the workflow.
> 
> But are you still planning to pull regular updates from the EP source corpus _manually_, right? This would somehow justify the extra work to keep EPDraCor a "living corpus" (I'm speaking of the changes from the EP side, not of our DraCor transformations).

Yes, I plan to pull updates from the EP sources in the future. Maybe not on a regular or automated schedule but more on an as needed basis.

> > Corrections of markup mistakes should ideally be done in epdracor-sources to integrate them into the transformation workflow
> 
> So, if I understand that correctly, is it possible to correct markup in `epdracor-sources` **with the changes being preserved** with every update from the source corpus? Or does any new update rewrite the `sources` repository, making this work useless? Thanks for clarifying!

In `epdracor-sources` there is a `dracor` branch where we can make corrections. The idea is to replay or merge those changes each time the main branch is updated from the original EP repo (in git terms the `dracor` branch is rebased). So, yes, changes on the `dracor` branch should survive an update from the originals. There is a chance of conflicting changes, which must be resolved after an update.

I suggest that we have a talk about this workflow when I'm back from vacations in March if you plan to go this route.

**Pull request merged**
